### ISSUE TITLE
Failed testSBOL

### ISSUE THREAD

**Issue by eyesmo** [SynBioDex/pySBOL#132]
Running in a Colab notebook, most tests worked, but one failed:
>sbol.testSBOL()

======================================================================
ERROR: testCopyAndIncrementVersion (sbol.unit_tests.TestCopy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/sbol/unit_tests.py", line 727, in testCopyAndIncrementVersion
    comp_copy = comp.copy()
  File "/usr/local/lib/python3.6/dist-packages/sbol/libsbol.py", line 6816, in copy
    return _libsbol.ComponentDefinition_copy(self, *args)
RuntimeError: Cannot add http://sbols.org/CRISPR_Example/foo/1.0.0 to Document. An object with this URI already exists. See validation rule sbol-10202.

----------------------------------------------------------------------
Ran 52 tests in 0.434s

FAILED (errors=1)

**Comment by bbartley** [comment]
Hi @eyesmo this is an expected failure on linux systems specifically.  This test covers an edge case that you likely won't need to worry about.  The library is still safe to use.

**Comment by eyesmo** [comment]
Good to know, thanks!

**Comment by jakebeal** [comment]
@bbartley Is there a way that we can mark it as expected failure for linux?
